package web

// client_parity_test.go verifies that client configs (URIs / .conf) generated by
// buildClientURI / buildAWGClientConf / buildConnectionLink actually carry the
// server-side credentials (public key, short id, uuid, port, SNI, transport)
// that the server config is built from. This is the "client config must match the
// server config" parity check — guards against the class of bug where the UI
// hallucinates a client link whose keys don't correspond to the server inbound.
//
// We test the link builders in isolation (no SSH / no remote apply): we feed in
// known server-side values and assert they appear verbatim in the produced link.

import (
	"encoding/base64"
	"net/url"
	"strings"
	"testing"

	"github.com/alexeylcp/angry-box/internal/chain"
	"github.com/alexeylcp/angry-box/internal/domain/model"
)

func initDefaultProfile(t *testing.T) {
	t.Helper()
	chain.SetDefaultProfile("maximum_stealth_2026")
}

// mustContain fails the test if sub is not in s.
func mustContain(t *testing.T, s, sub, label string) {
	t.Helper()
	if !strings.Contains(s, sub) {
		t.Errorf("%s: link missing %q\nlink: %s", label, sub, s)
	}
}

// mustNotContain fails the test if sub IS in s (used to catch placeholder/garbage).
func mustNotContain(t *testing.T, s, sub, label string) {
	t.Helper()
	if strings.Contains(s, sub) {
		t.Errorf("%s: link unexpectedly contains %q\nlink: %s", label, sub, s)
	}
}

// ---- AWG ----

func TestClientLink_AWG_ChainCarriesServerPublicKey(t *testing.T) {
	initDefaultProfile(t)
	// Server side stores the entry node's AWG public key in chain.AWGEntryServerPub.
	// buildConnectionLink must surface that exact key in the client link.
	c := &model.Chain{
		Name:              "awg-chain",
		UserProtocol:      model.UserProtocolAWG,
		AWGEntryServerPub: "SERVERPUB_BASE64_43chars___________",
		Nodes:             []model.ChainNode{{ID: "n1", Addr: "203.0.113.7:22"}},
	}
	link := buildConnectionLink(c, &model.User{ID: "u1"})
	mustContain(t, link, "203.0.113.7", "AWG chain IP")
	mustContain(t, link, "SERVERPUB_BASE64_43chars___________", "AWG server public key")
	mustContain(t, link, "awg://", "AWG scheme")
	// Must NOT fall back to a tun/direct placeholder when a real key is present.
	mustNotContain(t, link, "10.8.0.", "AWG chain link (should be URI, not .conf)")
}

func TestClientLink_AWG_StandaloneConfMatchesServer(t *testing.T) {
	initDefaultProfile(t)
	// A standalone AWG inbound stores ServerPubKey + an AWGClientPriv on the node.
	// The client .conf must carry the SAME ServerPubKey in [Peer]PublicKey.
	ib := model.NodeInbound{
		Protocol:      "awg",
		Port:          51820,
		ServerPubKey:  "PEER_PUBKEY_BASE64_43chars__________",
		AWGClientPriv: "CLIENT_PRIVKEY_BASE64_43chars________",
		AWGClientPub:  "CLIENT_PUBKEY_BASE64_43chars_________",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "[Interface]", "AWG .conf interface section")
	mustContain(t, link, "CLIENT_PRIVKEY_BASE64_43chars________", "AWG client private key")
	mustContain(t, link, "PEER_PUBKEY_BASE64_43chars__________", "AWG server public key parity")
	mustContain(t, link, "203.0.113.7:51820", "AWG endpoint (ip:port parity)")
	mustContain(t, link, "Jc = ", "AWG .conf amnezia Jc")
}

// ---- TUIC ----

func TestClientLink_TUIC_ChainCarriesUUIDAndPassword(t *testing.T) {
	initDefaultProfile(t)
	// Server-side TUIC inbound uses TUICEntryUserUUID/Password; the client link
	// must carry the SAME uuid:password so the client authenticates.
	c := &model.Chain{
		Name:                 "tuic-chain",
		UserProtocol:         model.UserProtocolTUIC,
		TUICEntryUserUUID:    "11111111-2222-3333-4444-555555555555",
		TUICEntryUserPassword: "tuic-pass-xyz",
		Nodes:                []model.ChainNode{{ID: "n1", Addr: "203.0.113.7:22"}},
	}
	link := buildConnectionLink(c, &model.User{ID: "u1"})
	mustContain(t, link, "tuic://", "TUIC scheme")
	mustContain(t, link, "11111111-2222-3333-4444-555555555555", "TUIC uuid parity")
	mustContain(t, link, "tuic-pass-xyz", "TUIC password parity")
	mustContain(t, link, "203.0.113.7:8443", "TUIC endpoint parity")
}

// ---- VLESS REALITY ----

func TestClientLink_VLESSReality_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	// Server inbound stores Reality public key (ServerPubKey) + ShortID.
	ib := model.NodeInbound{
		Protocol:      "vless-reality",
		Port:          443,
		UUID:          "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
		ServerPubKey:  "REALITY_PUBKEY_BASE64URL_43chars_____",
		ShortID:       "1a2b3c4d",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "vless://", "VLESS scheme")
	mustContain(t, link, "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "VLESS uuid parity")
	mustContain(t, link, "REALITY_PUBKEY_BASE64URL_43chars_____", "Reality public key parity")
	mustContain(t, link, "pbk=REALITY_PUBKEY_BASE64URL_43chars_____", "Reality pbk param")
	mustContain(t, link, "sid=1a2b3c4d", "Reality short id parity")
	mustContain(t, link, "203.0.113.7:443", "VLESS endpoint parity")
	mustContain(t, link, "security=reality", "Reality security")
	mustContain(t, link, "flow=xtls-rprx-vision", "Reality flow")
}

// ---- VLESS REALITY+XHTTP ----

func TestClientLink_VLESSRealityXHTTP_UsesServerSNI(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol:     "vless-reality-xhttp",
		Port:         443,
		UUID:         "aaaa1111-bbbb-cccc-dddd-eeeeeeeeeeee",
		ServerPubKey: "RXHTTP_PUBKEY_BASE64URL_43chars______",
		ShortID:      "deadbeef",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "vless://", "scheme")
	mustContain(t, link, "type=xhttp", "xhttp transport")
	mustContain(t, link, "security=reality", "reality security")
	mustContain(t, link, "RXHTTP_PUBKEY_BASE64URL_43chars______", "Reality pubkey parity")
	mustContain(t, link, "pbk=RXHTTP_PUBKEY_BASE64URL_43chars______", "pbk param")
	mustContain(t, link, "sid=deadbeef", "short id parity")
	mustContain(t, link, "mode=packet-up", "xhttp packet-up mode")
	// SNI must come from the active preset (not a hardcoded fallback in the link
	// when the preset defines one).
	preset := chain.GetDefaultPreset()
	if preset.Reality != nil && len(preset.Reality.ServerNames) > 0 {
		mustContain(t, link, url.QueryEscape(preset.Reality.ServerNames[0]), "preset SNI parity")
	}
}

// ---- Trojan ----

func TestClientLink_Trojan_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol:      "trojan",
		Port:          443,
		ServerPrivKey: "trojan-password-secret",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "trojan://", "Trojan scheme")
	mustContain(t, link, "trojan-password-secret", "Trojan password parity")
	mustContain(t, link, "203.0.113.7:443", "Trojan endpoint parity")
	mustContain(t, link, "security=tls", "Trojan TLS")
}

// ---- Shadowsocks ----

func TestClientLink_Shadowsocks_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol:      "shadowsocks",
		Port:          8388,
		ServerPrivKey: "ss-password-123",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "ss://", "SS scheme")
	mustContain(t, link, "203.0.113.7:8388", "SS endpoint parity")
	// userinfo = base64(cipher:password); the password must be embedded (not empty).
	mustNotContain(t, link, ":@203", "SS userinfo must not be empty (password parity)")
}

func TestBuildClientURI_SS_EmbedsCipherAndPassword(t *testing.T) {
	initDefaultProfile(t)
	link := buildClientURI("ss", "203.0.113.7", 8388, "", "ss-pass-9", "", "", "u1", &model.User{ID: "u1"})
	mustContain(t, link, "ss://", "SS scheme")
	mustContain(t, link, "203.0.113.7:8388", "SS endpoint parity")
	// The password must be embedded (base64-encoded userinfo).
	if strings.Contains(link, ":@203.0.113.7") {
		t.Errorf("SS link has empty userinfo (password not embedded): %s", link)
	}
}

// ---- Hysteria2 ----

func TestClientLink_Hysteria2_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol: "hysteria2",
		Port:     443,
		UUID:     "hysteria-uuid-value",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "hysteria2://", "Hysteria2 scheme")
	mustContain(t, link, "hysteria-uuid-value", "Hysteria2 uuid parity")
	mustContain(t, link, "203.0.113.7:443", "Hysteria2 endpoint parity")
	mustContain(t, link, "obfs=salamander", "Hysteria2 obfs")
}

// ---- MTProxy ----

func TestClientLink_MTProxy_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol: "mtproxy",
		Port:     443,
		UUID:     "0123456789abcdef0123456789abcdef",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "tg://proxy", "MTProxy scheme")
	mustContain(t, link, "203.0.113.7", "MTProxy server parity")
	mustContain(t, link, "443", "MTProxy port parity")
	// Secret must be the full ee+secret+hex(domain) form, not just the raw secret.
	mustContain(t, link, "ee0123456789abcdef0123456789abcdef", "MTProxy full secret (ee-prefixed)")
}

// ---- VMess ----

func TestClientLink_VMess_StandaloneParity(t *testing.T) {
	initDefaultProfile(t)
	ib := model.NodeInbound{
		Protocol: "vmess",
		Port:     443,
		UUID:     "vmess-uuid-1234",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustContain(t, link, "vmess://", "VMess scheme")
	// VMess link = base64(JSON{v,ps,add,port,id,aid,net,type,tls}). Decode the
	// payload and assert the server-side uuid + ip + port are embedded.
	payload := strings.TrimPrefix(link, "vmess://")
	dec, err := base64.StdEncoding.DecodeString(payload)
	if err != nil {
		t.Fatalf("vmess payload not valid base64: %v\nlink: %s", err, link)
	}
	body := string(dec)
	mustContain(t, body, `"add":"203.0.113.7"`, "VMess add (ip) parity")
	mustContain(t, body, `"port":"443"`, "VMess port parity")
	mustContain(t, body, `"id":"vmess-uuid-1234"`, "VMess uuid parity")
	mustContain(t, body, `"v":"2"`, "VMess version")
}

// ---- Empty/garbage guard ----

func TestClientLink_NoPlaceholderWhenFieldsPresent(t *testing.T) {
	initDefaultProfile(t)
	// If a real public key is supplied, the link must NEVER contain the
	// "fake/tun/direct" fallback marker that the v0.1.0 refactor removed.
	ib := model.NodeInbound{
		Protocol:     "vless-reality",
		Port:         443,
		UUID:         "u1",
		ServerPubKey: "REALPUB",
		ShortID:      "abcd1234",
	}
	link := buildStandaloneLink("203.0.113.7", ib, &model.User{ID: "u1"})
	mustNotContain(t, link, "fake", "no fake marker")
	mustNotContain(t, link, "placeholder", "no placeholder marker")
	mustNotContain(t, link, "TODO", "no TODO marker")
}